language: python
services:
- docker
sudo: required
addons:
  chrome: stable
before_install:
- docker-compose --env-file .env build
- docker-compose --env-file .env up -d
- docker-compose exec web bash /evoting/init_migrate_db.sh --load-template-data
- docker ps -a
script:
- docker-compose exec web python /evoting/manage.py test tests/
