language: python
services:
- docker
sudo: required
addons:
  chrome: stable
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- pwd
- ls -lha
- docker-compose --version
- docker-compose --env-file .env build
- docker-compose --env-file .env up -d
- docker-compose exec web bash /evoting/init_migrate_db.sh --load-template-data
- docker ps -a
script:
- docker-compose exec web python /evoting/manage.py test tests/
