version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
        - .env
    volumes:
      - .:/evoting
    ports:
      - "8000:8000"
    depends_on:
      - db