version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    command: bash -c "sleep 20 ; python manage.py runserver 0.0.0.0:8000"
    env_file:
        - .env
    volumes:
      - .:/evoting
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    links: 
      - db