# Generated by Django 2.1.2 on 2018-10-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('agendaURL', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('posID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('canVoteFor', models.CharField(max_length=100)),
                ('posName', models.CharField(max_length=200)),
                ('batch', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('voterID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hasVoted', models.BooleanField(default=False)),
                ('dateTime', models.DateTimeField(verbose_name='date voted')),
                ('batch', models.IntegerField(default=0)),
                ('hostel', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='votes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=15)),
                ('voteJSON', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='votes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=15)),
                ('voteJSON', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Positions'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Voters'),
        ),
    ]
