# Generated by Django 2.1.3 on 2018-11-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configvars',
            options={'verbose_name_plural': 'Poll Control Panel'},
        ),
    ]
