# Generated by Django 2.1.3 on 2018-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181107_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='webmail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
