# Generated by Django 2.1.3 on 2018-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181104_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucketName', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('hostel', models.CharField(choices=[('BH1', 'Boys-Hostel1'), ('GH1', 'Girls-Hostel1')], max_length=3)),
                ('year', models.IntegerField(choices=[(15, '15'), (16, '16'), (17, '17'), (18, '18')])),
                ('course', models.CharField(choices=[('B', 'BTech'), ('M', 'MTech'), ('P', 'Phd')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='tokenid',
            old_name='tokenId',
            new_name='tokenID',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='voterID',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='canVoteFor',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='positions',
            name='buckets',
            field=models.ManyToManyField(to='polls.Bucket'),
        ),
    ]
