# Generated by Django 2.2 on 2018-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181104_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='year',
            field=models.IntegerField(choices=[(0, 'All'), (15, '15'), (16, '16'), (17, '17'), (18, '18')]),
        ),
    ]
